nav:
  - Home: index.md

  ### MODIFY THE FOLLOWING TO UPDATE CONTENT
  - Core Practices:
    - content/practices/core-practices.md
    - Teaming, Ceremonies & Collaboration:
      - content/practices/balanced-team.md
      - content/practices/AgileCeremonies.md
    - DevSecOps:
      - content/practices/ci-cd.md
      - content/practices/version-control-systems.md 
      - content/practices/automated-testing.md
    - Product & Design:
      - content/practices/Human Centered Design.md
      - content/practices/discovery-and-framing.md
      - content/practices/measure-learn-iterate.md
      - content/practices/UserResearch.md

  - Plays: # All content for plays are referenced here
    - Cross-Discipline:
      - content/plays/cross-discipline/discovery-framing-remote.md
      - content/plays/cross-discipline/standup.md
      - content/plays/cross-discipline/iteration-sprint-planning.md
      - content/plays/cross-discipline/stakeholder-demo.md
    - Product:
      - content/plays/product/vision-statement.md
      - content/plays/product/product-strategy.md
      - content/plays/product/product-plays-OutcomeRoadmap.md
      - content/plays/product/story-writing.md
      - content/plays/product/backlog-prioritization.md
      - content/plays/product/product-release.md
    - Design:
      - content/plays/design/assumptions-workshop.md
      - content/plays/design/user-research-planning-play.md
      - content/plays/design/Interview-Discussion-Guide.md
      - content/plays/design/design-studio.md
      - content/plays/design/test.md
    - Engineering:
      - content/plays/engineering/coming-soon.md

  - Roles: # All content for roles are referenced here
    - content/roles/Product-Management-Role-Definition.md
    - content/roles/Product-Design-Role-Definition.md
    - content/roles/Engineering-Role-Definition.md

### PLEASE DONT TOUCH ANYTHING BELOW THIS POINT

# Configuration for analytics
extra:
  analytics:
    provider: google
    property: G-TLK83CLMXL

# Configuration for mkdocs theme
theme:
  custom_dir: material/overrides
  name: material
  logo: logo-rise8.svg
  favicon: https://rise8.us/images/favicons/cropped-rise8-favicon-32x32.png
  palette:
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.emoji

site_name: Delivery Playbooks
site_url: https://delivery-playbooks.rise8.us
