nav:
  - Home: index.md

  ### MODIFY THE FOLLOWING TO UPDATE CONTENT
  - Practices: # All content for practices are referenced here
    - Product:
      - content/practice/product/product-example-practice.md
    - Design:
      - content/practice/design/design-example-practice.md
    - Engineering:
      - content/practice/engineering/engineering-example-practice.md

  - Roles: # All content for roles are referenced here
    - Product:
      - content/roles/product/product-example-role.md
    - Design:
      - content/roles/design/design-example-role.md
    - Engineering:
      - content/roles/engineering/engineering-example-role.md

  - Plays: # All content for plays are referenced here
    - Product:
      - content/plays/product/product-example-play.md
    - Design:
      - content/plays/design/design-example-play.md
    - Engineering:
      - content/plays/engineering/engineering-example-play.md

### PLEASE DONT TOUCH ANYTHING BELOW THIS POINT

# Configuration for analytics
extra:
  analytics:
    provider: google
    property: G-TLK83CLMXL

# Configuration for mkdocs theme
theme:
  custom_dir: material/overrides
  name: material
  logo: logo-rise8.svg
  favicon: https://rise8.us/images/favicons/cropped-rise8-favicon-32x32.png
  palette:
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.emoji

site_name: Delivery Playbooks
site_url: https://delivery-playbooks.rise8.us